deb: Stop using `--wait` option of systemctl
fluent/fluent-package-builder pull request #526
Opened 2023-07-17 15:15 UTC by daipom

We misunderstood the use of this option.

By default, `systemctl status` waits until the unit's start-up is completed (without `--no-block` option).
The option `--wait` is for blocking `systemctl start foobar` until the service `foobar` is stopped.

2023-07-17 15:18 UTC, daipom commented
Note: `$ man systemctl` on Ubuntu 22.04.

```
       --no-block
           Do not synchronously wait for the requested operation to finish. If this is not specified, the job will be verified, enqueued and systemctl will wait until the unit's start-up is completed. By passing this argument, it is
           only verified and enqueued. This option may not be combined with --wait.
```

```
       --wait
           Synchronously wait for started units to terminate again. This option may not be combined with --no-block. Note that this will wait forever if any given unit never terminates (by itself or by getting stopped explicitly);
           particularly services which use "RemainAfterExit=yes".

           When used with is-system-running, wait until the boot process is completed before returning.
```

2023-07-18 00:36 UTC, ashie approved these changes
LGTM

I couldn't understand the document what `--wait` does, so I read the source code:
```console
aho@Ryzen:~/src/systemd-249.11/src/systemctl$ grep -rn arg_wait
systemctl.c:70:bool arg_wait = false;
systemctl.c:634:                        arg_wait = true;
systemctl.c:937:        if (arg_wait && arg_no_block)
systemctl.c:949:                if (arg_wait)
systemctl-start-unit.c:274:        if (arg_wait && !STR_IN_SET(argv[0], "start", "restart"))
systemctl-start-unit.c:280:        r = acquire_bus(arg_wait ? BUS_FULL : BUS_MANAGER, &bus);
systemctl-start-unit.c:354:        if (arg_wait) {
systemctl-start-unit.c:396:        if (arg_wait) {
systemctl.h:54:extern bool arg_wait;
systemctl-is-system-running.c:44:        if (arg_wait) {
systemctl-is-system-running.c:57:                        arg_wait = false;
systemctl-is-system-running.c:70:        if (arg_wait && STR_IN_SET(state, "initializing", "starting")) {
```
It's only affected on `systemctl start` or `systemctl is-system-running`, not affected to `status`.

2023-07-18 00:41 UTC, ashie requested changes
> By default, systemctl status waits until the unit's start-up is completed (without --no-block option).
--wait is an option about terminating, and has nothing to do with the start-up.

Could you revise this comment?
The option `--wait` is for blocking `systemctl start foobar` until the service `foobar` is stopped.

2023-07-18 00:45 UTC, daipom commented
Thanks for your review! I see!

The commit message and the issue comment is updated!

2023-07-18 00:46 UTC, ashie approved these changes
LGTM

2023-07-18 00:47 UTC, merged

2023-07-18 00:47 UTC, daipom commented
Thanks!