msi: fix wrong env path for Fluent Package Prompt
fluent/fluent-package-builder pull request #606
Opened 2023-12-12 04:27 UTC by daipom

* close #605

2023-12-12 04:28 UTC, daipom commented
I will check the behavior with the package built on the CI.

2023-12-12 07:22 UTC, kenhys commented
NOTE:   Additionally, `%~dp0\bin` expanded to `c:\fluent\\bin` for example, so there
    is no need to add path separator for it.

```diff
diff --git a/fluent-package/msi/assets/fluent-package-prompt.bat b/fluent-package/msi/assets/fluent-package-prompt.bat
index 96ec212..077877e 100644
--- a/fluent-package/msi/assets/fluent-package-prompt.bat
+++ b/fluent-package/msi/assets/fluent-package-prompt.bat
@@ -1,4 +1,4 @@
 @echo off
-set "PATH=%~dp0\bin;%PATH%"
+set "PATH=%~dp0bin;%PATH%"
 set "PATH=%~dp0;%PATH%"
 title Fluent Package Command Prompt
-- 
2.43.0
```

2023-12-12 07:31 UTC, daipom commented
> NOTE: Additionally, `%~dp0\bin` expanded to `c:\fluent\\bin` for example, so there is no need to add path separator for it.
> 
> ```diff
> diff --git a/fluent-package/msi/assets/fluent-package-prompt.bat b/fluent-package/msi/assets/fluent-package-prompt.bat
> index 96ec212..077877e 100644
> --- a/fluent-package/msi/assets/fluent-package-prompt.bat
> +++ b/fluent-package/msi/assets/fluent-package-prompt.bat
> @@ -1,4 +1,4 @@
>  @echo off
> -set "PATH=%~dp0\bin;%PATH%"
> +set "PATH=%~dp0bin;%PATH%"
>  set "PATH=%~dp0;%PATH%"
>  title Fluent Package Command Prompt
> -- 
> 2.43.0
> ```

Thanks! I see! I will add it.

2023-12-13 02:32 UTC, daipom commented
> > NOTE: Additionally, `%~dp0\bin` expanded to `c:\fluent\\bin` for example, so there is no need to add path separator for it.
> > ```diff
> > diff --git a/fluent-package/msi/assets/fluent-package-prompt.bat b/fluent-package/msi/assets/fluent-package-prompt.bat
> > index 96ec212..077877e 100644
> > --- a/fluent-package/msi/assets/fluent-package-prompt.bat
> > +++ b/fluent-package/msi/assets/fluent-package-prompt.bat
> > @@ -1,4 +1,4 @@
> >  @echo off
> > -set "PATH=%~dp0\bin;%PATH%"
> > +set "PATH=%~dp0bin;%PATH%"
> >  set "PATH=%~dp0;%PATH%"
> >  title Fluent Package Command Prompt
> > -- 
> > 2.43.0
> > ```
> 
> Thanks! I see! I will add it.

I will fix this in another PR after this PR is merged because this is not related to #605.

2023-12-13 02:33 UTC, daipom commented
I have confirmed the msi package works correctly.

2023-12-13 03:20 UTC, kenhys requested changes
The fixed content itself is reasonable, but it lacks the reason "why".

* PATH was set to "c:\opt\fluent";"c:\opt\fluent\\bin";...
* There is a case that some tool can't spawn td-agent-gem correctly when  PATH contains quoted literals...
* In this commit...

Could you amend commit message?

2023-12-13 03:55 UTC, daipom commented
> The fixed content itself is reasonable, but it lacks the reason "why".
> 
>     * PATH was set to "c:\opt\fluent";"c:\opt\fluent\bin";...
> 
>     * There is a case that some tool can't spawn td-agent-gem correctly when  PATH contains quoted literals...
> 
>     * In this commit...
> 
> 
> Could you amend commit message?

Thanks for your review. I have added it.

2023-12-13 04:27 UTC, kenhys approved these changes
LGTM.

2023-12-13 04:27 UTC, merged